- name: configuration of mysql
  hosts: mysql
  become: yes
  tasks:
    - name: installing mysql server
      ansible.builtin.package:
        name: mysql-server
        state: present
    
    - name: starting the service
      ansible.builtin.service:
        name: mysqld
        enabled: yes
        state: started

    - name: settingup mysql password
      vars:
        mysql_root_password: "RoboShop@1"
        community.mysql.mysql_user:
            name: root
            password: "{{ mysql_root_password }}"
            host_all: yes
            check_implicit_admin: yes  # Allows first-time login without a password
            state: present
            login_unix_socket: /var/lib/mysql/mysql.sock # Use /var/run/mysqld/mysqld.sock on Ubuntu