- name: instaling reddis 
  hosts: redis
  become: yes
  tasks:
    - name: disabling redis default module
      ansible.builtin.command: dnf module disable redis -y

    - name: enabiling redis
      ansible.builtin.command: dnf module enable redis:7 -y

    - name: installing redis
      ansible.builtin.dnf:
        name: redis 
        state: started
      
