- name: configuration of shipping module
  hosts: shipping
  become: yes
  tasks:
    - name: installing maven and mysql
      ansible.builtin.package:
        name: "{{item}}"
        state: present
      loop:
        -maven
        -mysql

    - name: installing pyMysql and cryptography
      ansible.builtn.pip:
        name: "{{item}}"
        executable: pip3.9
      loop:
        -cryptography
        -pyMysql
      
    - name: setting up roboshop user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        system: true
        home: /app
    
    - name: creating app directory
      ansible.builtin.file:
        path: app
        state: directory

    - name: downloading the shipping code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
        dest: /tmp/shipping.zip

    - name: unzipping the shipping
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app/
        remote_src: yes

    - name: installing maven dependentes
      ansible.builtin.command: mvn clean package
      args:
        chdir: /app

    - name: renaming the jar file
      ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
      args:
        chdir: /app

    - name: copying the service file
      ansible.builtin.copy:
        src: catalogue.service
        dest:  /etc/systemd/system/shipping.service

      
    - name: reloading the service
      ansible.builtin.systemd:
        name: shipping.service
        daemon_reload: yes
        state: started
        enabled: yes

    - name: importing data into mysql
      tags:
        -import
      community.mysql.mysql_db:
        name: all
        login_user: root
        login_password: RoboShop@1
        login_host: mysql.daws84.cyou
        state: import
        target: "{{item}}"
      loop:
        -/app/db/schema.sql
        -/appp/db/app-user.sql
        -/app/db/master-data.sql

    - name: restarting the service
      tags:
        - import
      ansible.builtin.systemd:
        name: shipping.service
        state: restarted


