- name: configuration of shipping module
  hosts: shipping
  become: yes
  tasks:
    - name: installing maven
      ansible.builtin.package:
        name: maven
        state: present
      
    - name: setting up roboshop user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        system: true
        home: /app
    
    - name: creating app directory
      ansible.builtin.file:
        path: app
        state: directory

    - name: downloading the shipping code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
        dest: /tmp/shipping.zip

    - name: unzipping the shipping
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app/
        remote_src: yes

    - name: installing maven dependentes
      ansible.builtin.command: mvn clean package
      args:
        chdir: /app

    - name: renaming the jar file
      ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
      args:
        chdir: /app
      
    - name: reloading the service
      ansible.builtin.systemd:
        name: shipping.service
        daemon_reload: yes
        state: started
        enabled: yes

    - name: installing mysql
      ansible.builtin.package:
        name: mysql 
        state: present

    - name: loading the schema into mysql
      ansible.builtin.shell: mysql -h mysql.daws84.cyou -uroot -pRoboShop@1 < /app/db/schema.sql

    - name: creating app user with password  into mysql
      ansible.builtin.shell: mysql -h mysql.daws84.cyou -uroot -pRoboShop@1 < /app/db/app-user.sql 
    
    - name: loading the cities data to mysql
      ansible.builtin.shell: mysql -h mysql.daws84.cyou -uroot -pRoboShop@1 < /app/db/master-data.sql

    - name: restarting the service
      ansible.builtin.systemd:
        name: shipping.service
        state: restarted
        

